services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  firstdockerapp:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "4000:4000"

volumes:
  mongodb-data:
